### ISSUE TITLE
No Gifts?

### ISSUE THREAD

**Issue by Catediali** [Calemi/ChristmasSpirit#1]
I am currently using the latest version of the mod on a singleplayer world. I am suppose to get a gift from Santa every day, but I am not receiving any gifts at all and it has been 4 IRL days. I tried typing in the command that will start the gifts, but the game keeps telling me I am typing it in wrong and then telling me to type it in the exact way I had previously done it. Ive tried typing it in multiple ways to no success. Is there any way to fix this?

**Comment by Calemi** [comment]
There should be a tab complete option when typing. If it doesn't show up, that's probably because cheats are turned off. A quick fix would be to open your world to LAN then enable cheats. Type in the command and you should be good to go. I realize this might be an issue for players that wouldn't want to open cheats, so I might change the perms for single players in a layer update. Let me know if this works!

**Comment by Calemi** [comment]
The exact command is 
```
/cspirit startDailyGiftEvent
```
